### ISSUE TITLE
When posting, "Excessive Spacing" button does not do anything

### ISSUE THREAD

**Issue by EvanSooHoo** [cbh123/shlinked#140]
If it works on your end, feel free to close

If you confirm that this is an issue, you can go ahead and assign it to me.

If you would prefer to fix it yourself, that is fine as well

<img width="383" alt="Screen Shot 2022-09-17 at 11 54 04 PM" src="https://user-images.githubusercontent.com/7552198/190889584-26b88b56-04ae-41ad-814c-a32c3666656f.png">

**Comment by cbh123** [comment]
Ah yes, this will only work if you have paragraph breaks. One nice thing you could add is a warning that nothing will happen if there aren't breaks? Up to you!
