### ISSUE TITLE
Migrations are out-of-sync with code

### ISSUE THREAD

**Issue by holmesjr** [cbh123/shlinked#37]
The articles table migrations, when run on a new DB, create a table that breaks the current code. They have `key` and `unicode` columns marked as not null, 

https://github.com/cbh123/shlinked/blob/main/priv/repo/migrations/20210119184707_add_emoji_and_description_to_articles.exs#L6

but the struct for an article doesn't contain these attributes and doesn't allow them to be saved:

https://github.com/cbh123/shlinked/blob/main/lib/shlinkedin/news/article.ex

**Comment by cbh123** [comment]
Update: turns out this migration file (https://github.com/cbh123/shlinked/blob/main/priv/repo/migrations/20210119184707_add_emoji_and_description_to_articles.exs#L6) was overwritten later on, so can be deleted.
