### ISSUE TITLE
Remove unused variables in tests

### ISSUE THREAD

**Issue by cbh123** [cbh123/shlinked#55]
I have quite a few declared but unused variables in my tests. These variables can be ignored by adding an `_` to the beginning of the name. 

For example, the error ```warning: variable "view" is unused (there is a variable with the same name in the context, use the pin operator (^) to match on it or prefix this variable with underscore if it is not meant to be used)
  test/shlinkedin_web/live/market_live_test.exs:38: ShlinkedinWeb.MarketLiveTest."test create an ad"/1```

can be fixed by adding an underscore to view. IE, going from:

```
    {:ok, view, html} = "blah blah blah"
```

to 

```
    {:ok, _view, html} = "blah blah blah"
```

# To Recreate
Run `mix test`. You will see warnings that looks like this: 
<img width="1246" alt="Screen Shot 2021-08-22 at 10 09 42 PM" src="https://user-images.githubusercontent.com/14149230/130380710-dd30425f-6e24-4257-b0f8-e78ca468d809.png">

**Comment by Onyinye91-ctrl** [comment]
Hello @cbh123 Can i work on this issue

**Comment by cbh123** [comment]
@Onyinye91-ctrl yes that would be a amazing!
