### ISSUE TITLE
hashtag button on content generator doesn't add spaces

### ISSUE THREAD

**Issue by skx** [cbh123/shlinked#65]
If you click the hashtag button on the content-generator it will append "#blah #blah" to the content-field, as expected.

Press it a second time and it will add more tags "#blah #blah", however it doesn't add any space before the addition - with the end result of:

```
#blah #blah#blah #blah
```

That breaks the tags.  I guess if the field doesn't end in a newline/whitespace a character should be injected prior to the (new) tag(s).

**Comment by cbh123** [comment]
Thanks, this is helpful. I'll take a look!

**Comment by skx** [comment]
Looks like this project isn't being developed, so closing to cleanup my issue-list.
