### ISSUE TITLE
Initial Ecto create fails with a type error

### ISSUE THREAD

**Issue by GaltMidas** [cbh123/shlinked#68]
Changed line 23 to 
field(:price, Money.Ecto.Amount.Type, default: 100)
from 
field(:price, Money.Ecto.Amount.Type, default: "100")
in defmodule Shlinkedin.Ads.Ad 

Otherwise it failed on mix ecto.create.  

Perhaps it's something in my own local setup.  Not sure.  But this did get things compiled.  Might prove calamitous to me down the road.  We'll see.

**Thanks** for this entire repo.  Quite a good deep dive down the LiveView rabbit hole.

**Comment by cbh123** [comment]
Thank you!! I can update this

**Comment by cbh123** [comment]
Thank you!! I can update this

**Comment by GaltMidas** [comment]
If you switch to MIT license, i'll do a PR

**Comment by cbh123** [comment]
> If you switch to MIT license, i'll do a PR

Not directly opposed, but curious why?
