### ISSUE TITLE
Relicense under the AGPL

### ISSUE THREAD

**Issue by wiki-me** [cbh123/shlinked#79]
the project is licensed under the GPL but because it runs on the server it can still be "stolen" and used as closed source so i suggest re-licensing it under the AGPL.

See the FSF [page](https://www.gnu.org/licenses/why-affero-gpl.en.html) and [wikipedia](https://en.wikipedia.org/wiki/Affero_General_Public_License) for details, but basically with the GPL someone can take your code , add a lot of code to it and because he is not distributing the software he will not release the changes (it is no longer reciprocal), then the proprietary competitor can become better then the open source version and attract all the users to him (possibly using more aggressive monetization) , with the AGPL he has to release the changes.

**Comment by cbh123** [comment]
Ok thanks, this is super helpful. I did not realize this

**Comment by cbh123** [comment]
updated. thanks again.

**Comment by wiki-me** [comment]
I forgot to mentioned it, IANAL but i am pretty sure you need the permission of other contributors to relicense  (although i don't think you will get sued over this).
